name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
       os: [ubuntu-16.04, ubuntu-18.04]
       compiler:
         - {
             cc: "gcc", cxx: "g++"
           }
         - {
             cc: "clang", cxx: "clang++"
           }
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install wheel setuptools
          pip3 install conan
      - name: Configure
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: ./configure
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest

  build-macos:
     runs-on: macOS-10.15
     steps:
       - uses: actions/checkout@v2
       - name: Install dependencies
         run: |
           brew install libomp
           pip3 install wheel setuptools
           pip3 install conan
       - name: Configure
         run: ./configure
       - name: Build
         run: cmake --build build
       - name: Test
         run: cd build && ctest
